<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>_RepairMaxDurability</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <Version>2.1.0</Version>
    <!-- The two lines below will set the output path for the binaries -->
    <OutputPath>bin\$(Configuration)\$(ProjectName)\$(AssemblyName)-$(Version)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <RunPostBuildEvent>Always</RunPostBuildEvent>
    <Configurations>Debug;Release;Source-Debug</Configurations>
  </PropertyGroup>
  
  <!-- Allow go to declaration using project source instead of decompiled source -->
  <ItemGroup Condition="'$(Configuration)'=='Source-Debug'">
    <ProjectReference Include="..\..\server-csharp\Libraries\SPTarkov.Server.Core\SPTarkov.Server.Core.csproj" />
    <ProjectReference Include="..\..\server-csharp\Libraries\SPTarkov.Common\SPTarkov.Common.csproj" />
    <ProjectReference Include="..\..\server-csharp\Libraries\SPTarkov.DI\SPTarkov.DI.csproj" />
  </ItemGroup>
  
  <ItemGroup Condition="'$(Configuration)'!='Source-Debug'">
    <PackageReference Include="SPTarkov.Server.Core" Version="4.0.0" />
    <PackageReference Include="SPTarkov.Common" Version="4.0.0" />
    <PackageReference Include="SPTarkov.DI" Version="4.0.0" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="PowerShell.exe -ExecutionPolicy Bypass -File &quot;$(ProjectDir)\PostBuild.ps1&quot; -Configuration &quot;$(ConfigurationName)&quot;" />
  </Target>

</Project>